samga/urls.py
from django.contrib import admin
from django.urls import path, include 
from django.conf import settings 
from django.conf.urls.static import static

from academy import views
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('', views.index),
    path('admin/', admin.site.urls),
    path('index/', views.index, name='index'),
    path('contact/', views.contact, name='contact'),
    path('faq/', views.faq, name='faq'),
    path('i18n/', include('django.conf.urls.i18n')),

    path('export/excel/', views.export_excel, name='export_excel'),     
    path('cabinet/', views.cabinet, name='cabinet'),

    path('teachers/index/', views.teachers_index, name='teachers_index'),
    path('teachers/list/', views.teachers_list, name='teachers_list'),
    path('teachers/create/', views.teachers_create, name='teachers_create'),
    path('teachers/edit/<int:id>/', views.teachers_edit, name='teachers_edit'),
    path('teachers/delete/<int:id>/', views.teachers_delete, name='teachers_delete'),
    path('teachers/read/<int:id>/', views.teachers_read, name='teachers_read'),

    path('training/index/', views.training_index, name='training_index'),
    path('training/create/', views.training_create, name='training_create'),
    path('training/edit/<int:id>/', views.training_edit, name='training_edit'),
    path('training/delete/<int:id>/', views.training_delete, name='training_delete'),
    path('training/read/<int:id>/', views.training_read, name='training_read'),

    path('groups/index/', views.groups_index, name='groups_index'),
    path('groups/create/', views.groups_create, name='groups_create'),
    path('groups/edit/<int:id>/', views.groups_edit, name='groups_edit'),
    path('groups/delete/<int:id>/', views.groups_delete, name='groups_delete'),
    path('groups/read/<int:id>/', views.groups_read, name='groups_read'),

    path('members/index/', views.members_index, name='members_index'),
    path('members/create/', views.members_create, name='members_create'),
    path('members/edit/<int:id>/', views.members_edit, name='members_edit'),
    path('members/delete/<int:id>/', views.members_delete, name='members_delete'),
    path('members/read/<int:id>/', views.members_read, name='members_read'),

    path('schedule/index/', views.schedule_index, name='schedule_index'),
    path('schedule/list/', views.schedule_list, name='schedule_list'),
    path('schedule/create/', views.schedule_create, name='schedule_create'),
    path('schedule/edit/<int:id>/', views.schedule_edit, name='schedule_edit'),
    path('schedule/delete/<int:id>/', views.schedule_delete, name='schedule_delete'),
    path('schedule/read/<int:id>/', views.schedule_read, name='schedule_read'),

    path('payment/index/', views.payment_index, name='payment_index'),
    path('payment/create/', views.payment_create, name='payment_create'),
    path('payment/edit/<int:id>/', views.payment_edit, name='payment_edit'),
    path('payment/delete/<int:id>/', views.payment_delete, name='payment_delete'),
    path('payment/read/<int:id>/', views.payment_read, name='payment_read'),

    path('reviews/index/', views.reviews_index, name='reviews_index'),
    path('reviews/list/', views.reviews_list, name='reviews_list'),
    path('reviews/create/', views.reviews_create, name='reviews_create'),
    path('reviews/delete/<int:id>/', views.reviews_delete, name='reviews_delete'),
    
    path('claim/index/', views.claim_index, name='claim_index'),
    path('claim/create/', views.claim_create, name='claim_create'),
    path('claim/edit/<int:id>/', views.claim_edit, name='claim_edit'),
    path('claim/delete/<int:id>/', views.claim_delete, name='claim_delete'),
    path('claim/read/<int:id>/', views.claim_read, name='claim_read'),

    path('news/index/', views.news_index, name='news_index'),
    path('news/list/', views.news_list, name='news_list'),
    path('news/create/', views.news_create, name='news_create'),
    path('news/edit/<int:id>/', views.news_edit, name='news_edit'),
    path('news/delete/<int:id>/', views.news_delete, name='news_delete'),
    path('news/read/<int:id>/', views.news_read, name='news_read'),

    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('settings/account/', views.UserUpdateView.as_view(), name='my_account'),
    path('password-reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('password-change/', auth_views.PasswordChangeView.as_view(), name='password_change'),
    path('password-change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

academy/models.py
from django.db import models
#from django.utils.translation import ugettext as _
from django.utils.translation import gettext_lazy as _

from PIL import Image
from PIL import ImageFile
ImageFile.LOAD_TRUNCATED_IMAGES = True
from django.core.files.storage import default_storage as storage  

from django.contrib.auth.models import User

import math

# Модели отображают информацию о данных, с которыми вы работаете.
# Они содержат поля и поведение ваших данных.
# Обычно одна модель представляет одну таблицу в базе данных.
# Каждая модель это класс унаследованный от django.db.models.Model.
# Атрибут модели представляет поле в базе данных.
# Django предоставляет автоматически созданное API для доступа к данным

# choices (список выбора). Итератор (например, список или кортеж) 2-х элементных кортежей,
# определяющих варианты значений для поля.
# При определении, виджет формы использует select вместо стандартного текстового поля
# и ограничит значение поля указанными значениями.

# Читабельное имя поля (метка, label). Каждое поле, кроме ForeignKey, ManyToManyField и OneToOneField,
# первым аргументом принимает необязательное читабельное название.
# Если оно не указано, Django самостоятельно создаст его, используя название поля, заменяя подчеркивание на пробел.
# null - Если True, Django сохранит пустое значение как NULL в базе данных. По умолчанию - False.
# blank - Если True, поле не обязательно и может быть пустым. По умолчанию - False.
# Это не то же что и null. null относится к базе данных, blank - к проверке данных.
# Если поле содержит blank=True, форма позволит передать пустое значение.
# При blank=False - поле обязательно.

# Преподаватели
class Teachers(models.Model):
    #user = models.OneToOneField(User, on_delete=models.CASCADE) 
    surname = models.CharField(_('surname'), max_length=64)
    name = models.CharField(_('name'), max_length=64)
    patronymic = models.CharField(_('patronymic'), max_length=64, blank=True, null=True)    
    details = models.TextField(_('details_teachers'))
    photo = models.ImageField(_('photo_teachers'), upload_to='images/', blank=True, null=True)    
    class Meta:
        # Параметры модели
        # Переопределение имени таблицы
        db_table = 'teachers'
        # indexes - список индексов, которые необходимо определить в модели
        indexes = [
            models.Index(fields=['surname']),
            models.Index(fields=['name']),
            models.Index(fields=['patronymic']),
        ]
        # Сортировка по умолчанию
        ordering = ['surname', 'name', 'patronymic']        
    def __str__(self):
        # Вывод в тег Select
        return "{} {} {}".format(self.surname, self.name, self.patronymic)
    @property
    def fio(self):
        # Возврат ФИО
        return '%s %s %s' % (self.surname, self.name, self.patronymic)
    @property
    def fio_shortcut(self):
        # Возврат Фамилия И.О.
        fio = self.surname + " "  + self.name[0] + "."
        if self.patronymic is not None:
            fio = fio + " " + self.patronymic[0] + "."
        return '%s' % (fio)

# Курс
class Training(models.Model):
    title = models.CharField(_('training_title'), unique=True, max_length=196)
    details = models.TextField(_('training_details'))
    class Meta:
        # Параметры модели
        # Переопределение имени таблицы
        db_table = 'training'
        # indexes - список индексов, которые необходимо определить в модели
        indexes = [
            models.Index(fields=['title']),
        ]
        # Сортировка по умолчанию
        ordering = ['title']
    def __str__(self):
        # Вывод Название в тег SELECT 
        return self.title

# Группы
class Groups(models.Model):
    training = models.ForeignKey(Training, related_name='groups_training', on_delete=models.CASCADE)
    title = models.CharField(_('group_title'), unique=True, max_length=256)
    details = models.TextField(_('group_details'))
    teachers = models.ForeignKey(Teachers, related_name='groups_teachers', on_delete=models.CASCADE)
    class Meta:
        # Параметры модели
        # Переопределение имени таблицы
        db_table = 'groups'
        # indexes - список индексов, которые необходимо определить в модели
        indexes = [
            models.Index(fields=['training']),
        ]
    def __str__(self):
        # Вывод Название в тег SELECT 
        return self.title

# Состав группы
class Members(models.Model):
    groups = models.ForeignKey(Groups, related_name='members_groups', on_delete=models.CASCADE)
    user = models.ForeignKey(User, related_name='members_user', on_delete=models.CASCADE)
    class Meta:
        # Параметры модели
        # Переопределение имени таблицы
        db_table = 'members'
        # indexes - список индексов, которые необходимо определить в модели
        indexes = [
            models.Index(fields=['groups']),
            models.Index(fields=['user']),
        ]
        # unique_together - уникальный индекс по нескольким полям
        unique_together = (
           'groups',
           'user',
        )

# Расписание занятий
class Schedule(models.Model):
    dates = models.DateTimeField(_('dates'))
    groups = models.ForeignKey(Groups, related_name='schedule_groups', on_delete=models.CASCADE)
    class Meta:
        # Параметры модели
        # Переопределение имени таблицы
        db_table = 'schedule'
        # indexes - список индексов, которые необходимо определить в модели
        indexes = [
            models.Index(fields=['dates']),
            models.Index(fields=['groups']),
        ]
        # Сортировка по умолчанию
        ordering = ['dates']
        # unique_together - уникальный индекс по нескольким полям
        unique_together = (
           'dates',
           'groups',
        )

# Оплата 
class Payment(models.Model):
    datep = models.DateTimeField(_('datep'))
    amount = models.DecimalField(_('amount'), max_digits=9, decimal_places=2)
    user = models.ForeignKey(User, related_name='payment_user', on_delete=models.CASCADE)
    class Meta:
        # Параметры модели
        # Переопределение имени таблицы
        db_table = 'payment'
        # indexes - список индексов, которые необходимо определить в модели
        indexes = [
            models.Index(fields=['datep']),
        ]
        # Сортировка по умолчанию
        ordering = ['datep']

# Отзывы 
class Reviews(models.Model):
    dater = models.DateTimeField(_('dater_reviews'), auto_now_add=True)
    rating = models.IntegerField(_('rating'), blank=True, null=True)
    details = models.TextField(_('details_reviews'))
    user = models.ForeignKey(User, related_name='reviews_user', on_delete=models.CASCADE)
    class Meta:
        # Параметры модели
        # Переопределение имени таблицы
        db_table = 'reviews'
        # indexes - список индексов, которые необходимо определить в модели
        indexes = [
            models.Index(fields=['dater']),
        ]
        # Сортировка по умолчанию
        ordering = ['dater']

# Заявки пользователей
class Claim(models.Model):
    dater = models.DateTimeField(_('dater_claim'), auto_now_add=True)
    user = models.ForeignKey(User, related_name='claim_user', on_delete=models.CASCADE)
    training = models.ForeignKey(Training, related_name='claim_training', on_delete=models.CASCADE)
    details = models.TextField(_('claim_details'))
    result = models.TextField(_('result'), blank=True, null=True)
    class Meta:
        # Параметры модели
        # Переопределение имени таблицы
        db_table = 'claim'
        # indexes - список индексов, которые необходимо определить в модели
        indexes = [
            models.Index(fields=['dater']),
        ]
        # Сортировка по умолчанию
        ordering = ['dater']
        
# Новости 
class News(models.Model):
    daten = models.DateTimeField(_('daten'))
    title = models.CharField(_('title_news'), max_length=256)
    details = models.TextField(_('details_news'))
    photo = models.ImageField(_('photo_news'), upload_to='images/', blank=True, null=True)    
    class Meta:
        # Параметры модели
        # Переопределение имени таблицы
        db_table = 'news'
        # indexes - список индексов, которые необходимо определить в модели
        indexes = [
            models.Index(fields=['daten']),
        ]
        # Сортировка по умолчанию
        ordering = ['daten']
    #def save(self):
    #    super().save()
    #    img = Image.open(self.photo.path) # Open image
    #    # resize image
    #    if img.width > 512 or img.height > 700:
    #        proportion_w_h = img.width/img.height  # Отношение ширины к высоте 
    #        output_size = (512, int(512/proportion_w_h))
    #        img.thumbnail(output_size) # Изменение размера
    #        img.save(self.photo.path) # Сохранение

templates/claim/create.html
{% extends "base.html" %}
{% load i18n %}
{% block title %}{% trans "Create" %}{% endblock title %}
{% block header %}{% endblock header %}
{% block content %}
<h2>{% trans "claim" %}</h2>
<form method="POST" enctype="multipart/form-data">
	{% csrf_token %}
    <table>
        {{ form }}
    </table>
	<div class="div-button-left">
		<button type="submit" class="btn btn-outline-success" style="width:100px">{% trans "Save" %}</button>	
		<button onclick="location.href='{% url 'claim_index' %}'" class="btn btn-outline-info" style="width:100px">{% trans "Back" %}</button>	
	</div>
</form>
<script type="text/javascript">
	$(".chosen").chosen();
</script>
{% endblock content %}

templates/claim/edit.html
{% extends "base.html" %}
{% load i18n %}
{% block title %}{% trans "Change" %}{% endblock title %}
{% block header %}{% endblock header %}
{% block content %}
<h2>{% trans "claim" %}</h2>
<form method="POST" enctype="multipart/form-data">
	{% csrf_token %}
	
	<table>
		<tr>
			<th><label for="id_user">{% trans "dater" %}</label></th>
			<td>{{ dater | date:"d.m.Y H:i"}}</td>
		</tr>
		<tr>
			<th><label for="id_user">{% trans "user" %}</label></th>
			<td>{{ user }}</td>
		</tr>
		<tr>
			<th><label for="id_training">{% trans "training" %}</label></th>
			<td>{{ training }}</td>
		</tr>
		<tr>
			<th><label for="id_details">{% trans "Claim_details" %}</label></th>
			<td>{{ details }}</td>
		</tr>
	</table>
	
	
    <table>
        {{ form }}
    </table>
	<div class="div-button-left">
		<button type="submit" class="btn btn-outline-success" style="width:100px">{% trans "Save" %}</button>
		<a class="btn btn-outline-info" style="width:100px" href="{% url 'claim_index' %}">{% trans "Back" %}</a>    
	</div>
</form>
<script type="text/javascript">
	$(".chosen").chosen();
</script>
{% endblock content %}

templates/claim/index.html
{% extends "base.html" %}
{% load i18n %}
{% block title %}{% trans "claims" %}{% endblock title %}
{% block header %}{% endblock header %}
{% block content %}
<h2>{% trans "claims" %}</h2>
{% if claim.count > 0 %}
<div class="row">
	<table id="myTable" class="table-manager" style="width:100%">
		<thead>
			<tr>
				<th><p>{% trans "dater" %}</p></th>
				<th><p>{% trans "training" %}</p></th>
				<th><p>{% trans "details" %}</p></th>
				<th><p>{% trans "result" %}</p></th>
				<th></th>				
			</tr>
		</thead>
		<tbody>
			{% for n in claim %}
			<tr>
				<td>
					<p>{{ n.dater | date:"d.m.Y H:i"}}</p>
					<p>{{ n.user }}, {{ n.user.first_name }} {{ n.user.last_name }}</p>
				</td>
				<td>
					<p>{{ n.training }}</p>						
				</td>
				<td>
					<p>{{ n.details }}</p>						
				</td>
				<td>
					<p>{{ n.result }}</p>						
				</td>
				<td>
					<a href="{% url 'claim_edit' n.id %}">{% trans "Change" %}</a> |
					<a href="{% url 'claim_read' n.id %}">{% trans "View" %}</a> |
					<a onclick="return confirm('Удалить запись?')" href="{% url 'claim_delete' n.id %}">{% trans "Delete" %}</a>
				</td>			
			</tr>
			{% endfor %}
		</tbody>
	</table>
</div>
{% else %}
<a href="{% url 'claim_create'%}">{% trans "Create" %}</a>
{% endif %}
{% endblock content %}

templates/claim/read.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}
{% block title %}{% trans "Read" %}{% endblock title %}
{% block header %}{% endblock header %}
{% block content %}
<h2>{% trans "claim" %}</h2>
<div class="row justify-content-center">
	<div class="card" style="width:100%">
		<div class="card-header">
			<p>{{ claim.dater | date:"d.m.Y H:i"}}</p>
			<h4>{{ claim.user }}, {{ claim.user.first_name }} {{ claim.user.last_name }}</h4>			
		</div>
		<div class="card-body">
			<p>{{ claim.training }}</p>						
			<p>{{ claim.details }}</p>					
			<p>{{ claim.result }}</p>					
		</div>
		<div class="card-footer">				
			<p></p>			
		</div>		
	</div>
	<div class="div-button-left">
		<a class="btn btn-outline-info" style="width:100px; margin-top:5px" href="{% url 'claim_index' %}">{% trans "Back" %}</a>    
	</div>
</div>

{% endblock content %}